---
title: Jupyter Notebooks for communication
author: e-Commons
copyright: "2024"
logo: content/static/E-COMMONS_CMYK_EN.png
exclude_patterns: [".DS_Store", "**.ipynb_checkpoints", ".virtual_documents/", "README.md"]

execute:
  execute_notebooks: auto

latex:
  latex_documents:
    targetname: book.tex
  latex_engine: xelatex

sphinx:
  config:
    html_theme: sphinx_book_theme
    html_js_files: https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    html_theme_options:
      use_download_button: true
      show_navbar_depth: 2
      extra_footer: <a href="https://www.chalmers.se/en/infrastructure/ecommons">e-Commons</a>
      toc_title: Content

parse:
  myst_enable_extensions:
    - html_image
    - colon_fence

# html:
#   favicon: imgs/favicon.ico
